
import React from 'react';
import { useSoccerSim } from './hooks/useSoccerSim';
import TeamInput from './components/TeamInput';
import Scoreboard from './components/Scoreboard';
import MatchLog from './components/MatchLog';
import Controls from './components/Controls';
import { SoccerBallIcon } from './components/icons/SoccerBallIcon';
import { GameState } from './types';

export default function App() {
  const {
    state,
    setHomeTeamName,
    setAwayTeamName,
    startGame,
    resetGame,
  } = useSoccerSim();

  const { gameState, homeTeam, awayTeam, matchLog, time, isLoading } = state;

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 to-gray-800 font-sans p-4 sm:p-6 md:p-8 flex flex-col items-center">
      <header className="w-full max-w-4xl text-center mb-6">
        <h1 className="text-4xl sm:text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-green-400 to-blue-500 flex items-center justify-center gap-3">
          <SoccerBallIcon className="w-8 h-8 sm:w-10 sm:h-10" />
          Gemini Soccer Simulator
        </h1>
        <p className="text-gray-400 mt-2 text-sm sm:text-base">
          Live match commentary powered by AI
        </p>
      </header>

      <main className="w-full max-w-4xl flex-grow flex flex-col bg-gray-800 bg-opacity-50 rounded-2xl shadow-2xl overflow-hidden backdrop-blur-sm border border-gray-700">
        {gameState === GameState.SETUP ? (
          <TeamInput
            homeTeamName={homeTeam.name}
            awayTeamName={awayTeam.name}
            setHomeTeamName={setHomeTeamName}
            setAwayTeamName={setAwayTeamName}
            onStartGame={startGame}
          />
        ) : (
          <div className="flex flex-col h-full">
            <Scoreboard homeTeam={homeTeam} awayTeam={awayTeam} time={time} gameState={gameState} />
            <MatchLog log={matchLog} isLoading={isLoading} />
            <Controls onReset={resetGame} gameState={gameState} />
          </div>
        )}
      </main>
      <footer className="w-full max-w-4xl text-center mt-6 text-gray-500 text-xs">
        <p>This is a simulation. Match events and commentary are generated by an AI and are not reflective of real games.</p>
      </footer>
    </div>
  );
}
